version: '3.8'
services:
  database:
    image: mongo:latest
    container_name: "node-gmp-nosql-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_user_password
      MONGO_INITDB_DATABASE: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro